delt/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from vocabs import api_views

if 'bib' in settings.INSTALLED_APPS:
    from bib.api_views import ZotItemViewSet

router = routers.DefaultRouter()
router.register(r'metadata', api_views.MetadataViewSet)
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skoscollections', api_views.SkosCollectionViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
if 'bib' in settings.INSTALLED_APPS:
    router.register(r'zotitems', ZotItemViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^assignments/', include('assignments.urls', namespace='assignments')),
    url(r'^admin/', admin.site.urls),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^shib/', include('shibboleth.urls', namespace='shibboleth')),
    url(r'^', include('webpage.urls', namespace='webpage')),
]

if 'bib' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^bib/', include('bib.urls', namespace='bib')),
    )

handler404 = 'webpage.views.handler404'

vocabs/urls.py
from django.conf.urls import url
from . import views
from . import dal_views
from .models import SkosLabel, SkosConcept, SkosConceptScheme, Metadata

app_name = 'vocabs'


urlpatterns = [
    url(r'^$', views.SkosConceptListView.as_view(), name='skosconcept_list'),
    url(r'^concepts/browse/$', views.SkosConceptListView.as_view(), name='browse_vocabs'),
    url(r'^(?P<pk>[0-9]+)$', views.SkosConceptDetailView.as_view(), name='skosconcept_detail'),
    url(r'^create/$', views.SkosConceptCreate.as_view(), name='skosconcept_create'),
    url(r'^update/(?P<pk>[0-9]+)$', views.SkosConceptUpdate.as_view(), name='skosconcept_update'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.SkosConceptDelete.as_view(), name='skosconcept_delete'),
    url(r'^scheme/$', views.SkosConceptSchemeListView.as_view(), name='browse_schemes'),
    url(
        r'^scheme/(?P<pk>[0-9]+)$', views.SkosConceptSchemeDetailView.as_view(),
        name='skosconceptscheme_detail'),
    url(
        r'^scheme/create/$', views.SkosConceptSchemeCreate.as_view(),
        name='skosconceptscheme_create'),
    url(
        r'^scheme/update/(?P<pk>[0-9]+)$', views.SkosConceptSchemeUpdate.as_view(),
        name='skosconceptscheme_update'),
    url(
        r'^scheme/delete/(?P<pk>[0-9]+)$',
        views.SkosConceptSchemeDelete.as_view(),
        name='skosconceptscheme_delete',
    ),
    url(r'^label/$', views.SkosLabelListView.as_view(), name='browse_skoslabels'),
    url(
        r'^label/(?P<pk>[0-9]+)$', views.SkosLabelDetailView.as_view(),
        name='skoslabel_detail'),
    url(
        r'^label/create/$', views.SkosLabelCreate.as_view(),
        name='skoslabel_create'),
    url(
        r'^label/update/(?P<pk>[0-9]+)$', views.SkosLabelUpdate.as_view(),
        name='skoslabel_update'),
    url(
        r'^skoslabel/delete/(?P<pk>[0-9]+)$',
        views.SkosLabelDelete.as_view(),
        name='skoslabel_delete',
    ),
    url(
        r'^metadata/$', views.MetadataListView.as_view(),
        name='metadata'),
    url(
        r'^metadata/(?P<pk>[0-9]+)$', views.MetadataDetailView.as_view(),
        name='metadata_detail'),
    url(
        r'^metadata/create/$', views.MetadataCreate.as_view(),
        name='metadata_create'),
    url(
        r'^metadata/update/(?P<pk>[0-9]+)$', views.MetadataUpdate.as_view(),
        name='metadata_update'),
    url(
        r'^metadata/delete/(?P<pk>[0-9]+)$', views.MetadataDelete.as_view(),
        name='metadata_delete',
    ),
     url(
        r'^collection/$', views.SkosCollectionListView.as_view(),
        name='browse_skoscollections'),
    url(
        r'^collection/(?P<pk>[0-9]+)$', views.SkosCollectionDetailView.as_view(),
        name='skoscollection_detail'),
    url(
        r'^collection/create/$', views.SkosCollectionCreate.as_view(),
        name='skoscollection_create'),
    url(
        r'^collection/update/(?P<pk>[0-9]+)$', views.SkosCollectionUpdate.as_view(),
        name='skoscollection_update'),
    url(
        r'^collection/delete/(?P<pk>[0-9]+)$',views.SkosCollectionDelete.as_view(),
        name='skoscollection_delete',
    ),
]

vocabs/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django_tables2 import SingleTableView, RequestConfig
from .models import SkosConcept, SkosConceptScheme, SkosLabel, SkosCollection, Metadata
from .forms import *
from .tables import *
from .filters import SkosConceptListFilter, SkosConceptSchemeListFilter, SkosLabelListFilter, SkosCollectionListFilter
from browsing.browsing_utils import GenericListView, BaseCreateView, BaseUpdateView


#####################################################
#   Metadata
#####################################################


class MetadataListView(ListView):

    model = Metadata
    template_name = 'vocabs/metadata_list.html'


class MetadataDetailView(DetailView):

    model = Metadata
    template_name = 'vocabs/metadata_detail.html'


class MetadataCreate(BaseCreateView):

    model = Metadata
    form_class = MetadataForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MetadataCreate, self).dispatch(*args, **kwargs)


class MetadataUpdate(BaseUpdateView):

    model = Metadata
    form_class = MetadataForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MetadataUpdate, self).dispatch(*args, **kwargs)


class MetadataDelete(DeleteView):
    model = Metadata
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('vocabs:metadata')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MetadataDelete, self).dispatch(*args, **kwargs)


#####################################################
#   SkosCollection
#####################################################


class SkosCollectionListView(GenericListView):
    model = SkosCollection
    table_class = SkosCollectionTable
    filter_class = SkosCollectionListFilter
    formhelper_class = SkosCollectionFormHelper
    init_columns = [
        'id',
        'name',
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosCollectionListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by
        }).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosCollectionDetailView(DetailView):

    model = SkosCollection
    template_name = 'vocabs/skoscollection_detail.html'


class SkosCollectionCreate(BaseCreateView):

    model = SkosCollection
    form_class = SkosCollectionForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosCollectionCreate, self).dispatch(*args, **kwargs)


class SkosCollectionUpdate(BaseUpdateView):

    model = SkosCollection
    form_class = SkosCollectionForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosCollectionUpdate, self).dispatch(*args, **kwargs)


class SkosCollectionDelete(DeleteView):
    model = SkosCollection
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('vocabs:browse_skoscollections')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosCollectionDelete, self).dispatch(*args, **kwargs)


#####################################################
#   Concept
#####################################################


class SkosConceptListView(GenericListView):
    model = SkosConcept
    table_class = SkosConceptTable
    filter_class = SkosConceptListFilter
    formhelper_class = SkosConceptFormHelper
    init_columns = [
        'id',
        'pref_label',
        'broader_concept',
    ]


class SkosConceptDetailView(DetailView):

    model = SkosConcept
    template_name = 'vocabs/skosconcept_detail.html'


class SkosConceptCreate(BaseCreateView):

    model = SkosConcept
    form_class = SkosConceptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptCreate, self).dispatch(*args, **kwargs)


class SkosConceptUpdate(BaseUpdateView):

    model = SkosConcept
    form_class = SkosConceptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptUpdate, self).dispatch(*args, **kwargs)


class SkosConceptDelete(DeleteView):
    model = SkosConcept
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('vocabs:browse_vocabs')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptDelete, self).dispatch(*args, **kwargs)


#####################################################
#   ConceptScheme
#####################################################


class SkosConceptSchemeListView(GenericListView):
    model = SkosConceptScheme
    table_class = SkosConceptSchemeTable
    filter_class = SkosConceptSchemeListFilter
    formhelper_class = SkosConceptSchemeFormHelper
    init_columns = [
        'id',
        'dc_title',
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosConceptSchemeListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by
        }).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosConceptSchemeDetailView(DetailView):

    model = SkosConceptScheme
    template_name = 'vocabs/skosconceptscheme_detail.html'

    def get_context_data(self, **kwargs):
        context = super(SkosConceptSchemeDetailView, self).get_context_data(**kwargs)
        context["concepts"] = SkosConcept.objects.filter(scheme=self.kwargs.get('pk'))
        return context


class SkosConceptSchemeCreate(BaseCreateView):

    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeCreate, self).dispatch(*args, **kwargs)


class SkosConceptSchemeUpdate(BaseUpdateView):

    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeUpdate, self).dispatch(*args, **kwargs)


class SkosConceptSchemeDelete(DeleteView):
    model = SkosConceptScheme
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('vocabs:browse_schemes')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeDelete, self).dispatch(*args, **kwargs)


###################################################
# SkosLabel
###################################################


class SkosLabelListView(GenericListView):
    model = SkosLabel
    table_class = SkosLabelTable
    filter_class = SkosLabelListFilter
    formhelper_class = SkosLabelFormHelper
    init_columns = [
        'id',
        'name',
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosLabelListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by
        }).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosLabelDetailView(DetailView):

    model = SkosLabel
    template_name = 'vocabs/skoslabel_detail.html'


class SkosLabelCreate(BaseCreateView):

    model = SkosLabel
    form_class = SkosLabelForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosLabelCreate, self).dispatch(*args, **kwargs)


class SkosLabelUpdate(BaseUpdateView):

    model = SkosLabel
    form_class = SkosLabelForm

    @method_decorator(login_required)

vocabs/templates/vocabs/confirm_delete.html
{% extends "vocabs/plain_for_delete.html" %}
{% block content %}
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
            <h3 class="modal-title">Confirm delete</h3>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="" method="post">{% csrf_token %}
                    <h4>Are you sure you want to delete :<br /> <strong>{{ object }}</strong> ?</h4><br />
                    <a href="javascript:history.back()"><input class="btn btn-default" type="button" value="cancel"/></a>
                    <input  class="btn btn-danger" type="submit" value="yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
</form>
{% endblock content %}
{% block scripts %}
    <script type="text/javascript">
        $(window).load(function(){
            $('#myModal').modal('show');
        });
    </script>
{% endblock scripts %}

vocabs/templates/vocabs/import_skos.html
{% extends "webpage/base.html" %}
{% block Title %} Import SKOS {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<div class="card">
    <div class="card-header">
        <h1 style="text-align: center;">Import SKOS</h1>
    </div>
    <div class="card-body">
        <h2 style="text-align: center;">{{ worked }}</h2><br />
        {% crispy form %}
        </div>
    </div>
</div>
{% endblock content %}

vocabs/templates/vocabs/metadata_list.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
{% if object_list %}
{% for x in object_list %}
<div class="card">
    <div class="card-header">
        <h1 style="text-align: center;">Metadata {{ x.title }}
        {% if user.is_authenticated %}
            <small>
                <a href="{% url 'vocabs:metadata_update' pk=x.id %}">
                    <i class="far fa-edit" title="edit"></i>
                </a>
            </small>
                |
            <small>
                <a href="{% url 'vocabs:metadata_delete' pk=x.id %}">
                    <i class="far fa-trash-alt" title="delete"></i>
                </a>
            </small>
         {% endif %}
        </h1>
    </div>
        <table class="table">
        <tr>
        	<th>Title</th>
        	<td>{{x.title}}</td>
        </tr>
        <tr>
        	<th>Indentifier</th>
        	<td>{{x.indentifier}}</td>
        </tr>
        <tr>
        	<th>Description</th>
        	<td>{{x.description}}</td>
        </tr>
        <tr>
        	<th>Description language</th>
        	<td>{{x.description_lang}}</td>
        </tr>
        <tr>
        	<th>Language</th>
        	<td>
        	{% if x.language %}
        	{% for language in x.language_as_list %}
    		<li>{{ language }}</li>
			{% endfor %}
			{% endif %}
			</td>
        </tr>
        <tr>
        	<th>Version</th>
        	<td>{{x.version}}</td>
        </tr>
        <tr>
        	<th>Creator</th>
        	<td>
            {% if x.creator %}
            {% for creator in x.creator_as_list %}
            <li>{{ creator }}</li>
            {% endfor %}
            {% endif %}    
            </td>
        </tr>
        <tr>
        	<th>Contributor</th>
        	<td>
            {% if x.contributor %}
            {% for contributor in x.contributor_as_list %}
            <li>{{ contributor }}</li>
            {% endfor %}
            {% endif %} 
            </td>
        </tr>
        <tr>
        	<th>Subject</th>
        	<td>
        	{% if x.subject %}
        	{% for subject in x.subject_as_list %}
    		<li>{{ subject }}</li>
			{% endfor %}
			{% endif %}
			</td>
        </tr>
        <tr>
        	<th>Owner</th>
        	<td>{{x.owner}}</td>
        </tr>
        <tr>
        	<th>License</th>
        	<td>{{x.license}}</td>
        </tr>
        <tr>
        	<th>Date created</th>
        	<td>{{x.date_created}}</td>
        </tr>
        <tr>
        	<th>Date modified</th>
        	<td>{{x.date_modified}}</td>
        </tr>
        <tr>
        	<th>Date issued</th>
        	<td>{{x.date_issued}}</td>
        </tr>
        <tr>
        	<th>Relation</th>
        	<td>{{x.relation}}</td>
        </tr>
        </table>
</div>
{% endfor %}
{% else %}
<a class="btn btn-outline-primary" href="{% url 'vocabs:metadata_create' %}">create Metadata</a>
{% endif %}
</div>
{% endblock %}

vocabs/templates/vocabs/skoscollection_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skoscollection_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>skos:Collection</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skoscollection_update' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skoscollection_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skoscollection_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
        <table class="table">
        {% if object.creator %}
         <tr>
            <th>dc:creator</th>
            <td>
            {% for creator in object.creator_as_list %}
            <li>{{ creator }}</li>
            {% endfor %}
            </td>
        </tr>
        {% endif %}

        {% if object.skos_note %}
         <tr>
            <th>skos:note</th>
            <td>{{object.skos_note}}</td>
        </tr>
        {% endif %}

        {% if object.skos_scopenote %}
         <tr>
            <th>skos:scopeNote</th>
            <td>{{object.skos_scopenote}}</td>
        </tr>
        {% endif %}

        {% if object.skos_changenote %}
         <tr>
            <th>skos:changeNote</th>
            <td>{{object.skos_changenote}}</td>
        </tr>
        {% endif %}

        {% if object.skos_editorialnote %}
         <tr>
            <th>skos:editorialNote</th>
            <td>{{object.skos_editorialnote}}</td>
        </tr>
        {% endif %}

        {% if object.skos_example %}
         <tr>
            <th>skos:example</th>
            <td>{{object.skos_example}}</td>
        </tr>
        {% endif %}

        {% if object.skos_historynote %}
         <tr>
            <th>skos:historyNote</th>
            <td>{{object.skos_historynote}}</td>
        </tr>
        {% endif %}

        {% if object.date_created %}
         <tr>
            <th>dct:created</th>
            <td>{{object.date_created}}</td>
        </tr>
        {% endif %}

        {% if object.date_modified %}
         <tr>
            <th>dct:modified</th>
            <td>{{object.date_modified}}</td>
        </tr>
        {% endif %}

        {% if object.has_members.all %}
        <tr>
        <th>skos:members</th>
        <td>
        {% for x in object.has_members.all %}
            <li>
                <a href="{{ x.get_absolute_url }}">{{ x }}</a>
            </li>
        {% endfor %}
        </td>
        </tr>
        {% endif %}

        </table>  
    </div>
</div>
{% endblock %}

vocabs/templates/vocabs/skosconcept_filter.html
{% extends "vocabs/generic_list.html" %}
{% block list_title %}Browse SkosConcepts{% endblock %}
{% block create_button %}
{% if user.is_authenticated %}
<div>
    <a class ="btn btn-primary"  href="{% url 'vocabs:skosconcept_create' %}">
        create new concept
    </a>
</div>
{% endif %}
{% endblock %}
{% block reset_button %}
    <a class ="btn btn-outline-secondary" href="{% url 'vocabs:browse_vocabs' %}">reset search</a>
{% endblock %}

vocabs/templates/vocabs/skosconceptscheme_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skosconceptscheme_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>skos:ConceptScheme</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skosconceptscheme_update' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skosconceptscheme_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skosconceptscheme_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
        <table class="table">
        {% if object.dc_title %}
        <tr>
            <th>dc:title</th>
            <td>{{object.dc_title}} {% if object.dc_title_lang %}@{{object.dc_title_lang}}{% endif %}</td>
        </tr>
        {% endif %}
        {% if object.dc_creator %}
        <tr>
        <th>dc:creator</th>
        <td>
        {% for creator in object.dc_creator_as_list %}
        <li>{{creator}}</li>
        {% endfor %}
        </td>
        </tr>
        {% endif %}
        {% if object.dc_description %}
        <tr>
            <th>dc:description</th>
            <td>{{object.dc_description}} {% if object.dc_description_lang %}@{{object.dc_description_lang}}{% endif %}</td>
        </tr>
        {% endif %}
        {% if object.legacy_id %}
        <tr>
            <th>legacy ID</th>
            <td>{{object.legacy_id}}</td>
        </tr>
        {% endif %}
        {% if object.date_created %}
         <tr>
            <th>dct:created</th>
            <td>{{object.date_created}}</td>
        </tr>
        {% endif %}
        {% if object.date_modified %}
         <tr>
            <th>dct:modified</th>
            <td>{{object.date_modified}}</td>
        </tr>
        {% endif %}
        {% if object.has_concepts.all %}
        <tr>
        <th>concepts skos:inScheme</th>
        <td>
        {% for x in object.has_concepts.all %}
            <li>
                <a href="{{ x.get_absolute_url }}">{{ x }}</a>
            </li>
        {% endfor %}
        </td>
        <tr>
        {% endif %}
        </table>       
    </div>
</div>
{% endblock %}

vocabs/templates/vocabs/skoslabel_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skoslabel_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>Label</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skoslabel_update' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skoslabel_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skoslabel_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
            <table class="table">
                <tr>
                    <th>Label</th>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <th>Label type</th>
                    <td>{{ object.label_type }}</td>
                </tr>
                <tr>
                    <th>IsoCode</th>
                    <td>{{ object.isoCode }}</td>
                </tr>
            </table>
    </div>
</div>
{% endblock %}