assignments/urls.py
from django.conf.urls import url
from . import views

app_name = 'assignments'

urlpatterns = [
    url(r'^assignments/$', views.AssignmentListView.as_view(), name='browse_assignments'),
    url(r'^assignment/detail/(?P<pk>[0-9]+)$', views.AssignmentDetailView.as_view(),
        name='assignment_detail'),
    url(r'^assignment/delete/(?P<pk>[0-9]+)$', views.AssignmentDelete.as_view(),
        name='assignment_delete'),
    url(r'^assignment/edit/(?P<pk>[0-9]+)$', views.AssignmentUpdate.as_view(),
        name='assignment_edit'),
    url(r'^assignment/create/$', views.AssignmentCreate.as_view(),
        name='assignment_create'),
    url(r'^texts/$', views.TextListView.as_view(), name='browse_texts'),
    url(r'^text/detail/(?P<pk>[0-9]+)$', views.TextDetailView.as_view(),
        name='text_detail'),
    url(r'^text/delete/(?P<pk>[0-9]+)$', views.TextDelete.as_view(),
        name='text_delete'),
    url(r'^text/edit/(?P<pk>[0-9]+)$', views.TextUpdate.as_view(),
        name='text_edit'),
    url(r'^text/create/$', views.TextCreate.as_view(),
        name='text_create'),
    url(r'^textversions/$', views.TextVersionListView.as_view(), name='browse_textversions'),
    url(r'^textversion/detail/(?P<pk>[0-9]+)$', views.TextVersionDetailView.as_view(),
        name='textversion_detail'),
    url(r'^textversion/delete/(?P<pk>[0-9]+)$', views.TextVersionDelete.as_view(),
        name='textversion_delete'),
    url(r'^textversion/edit/(?P<pk>[0-9]+)$', views.TextVersionUpdate.as_view(),
        name='textversion_edit'),
    url(r'^textversion/create/$', views.TextVersionCreate.as_view(),
        name='textversion_create'),
    url(r'^learners/$', views.LearnerListView.as_view(), name='browse_learners'),
    url(r'^learner/detail/(?P<pk>[0-9]+)$', views.LearnerDetailView.as_view(),
        name='learner_detail'),
    url(r'^learner/delete/(?P<pk>[0-9]+)$', views.LearnerDelete.as_view(),
        name='learner_delete'),
    url(r'^learner/edit/(?P<pk>[0-9]+)$', views.LearnerUpdate.as_view(),
        name='learner_edit'),
    url(r'^learner/create/$', views.LearnerCreate.as_view(),
        name='learner_create'),
    url(r'^learnerprofiles/$',
        views.LearnerProfileListView.as_view(), name='browse_learnerprofiles'
        ),
    url(r'^learnerprofile/detail/(?P<pk>[0-9]+)$', views.LearnerProfileDetailView.as_view(),
        name='learnerprofile_detail'),
    url(r'^learnerprofile/delete/(?P<pk>[0-9]+)$', views.LearnerProfileDelete.as_view(),
        name='learnerprofile_delete'),
    url(r'^learnerprofile/edit/(?P<pk>[0-9]+)$', views.LearnerProfileUpdate.as_view(),
        name='learnerprofile_edit'),
    url(r'^learnerprofile/create/$', views.LearnerProfileCreate.as_view(),
        name='learnerprofile_create'),
    url(r'^coursegroups/$',
        views.CourseGroupListView.as_view(), name='browse_coursegroups'
        ),
    url(r'^coursegroup/detail/(?P<pk>[0-9]+)$', views.CourseGroupDetailView.as_view(),
        name='coursegroup_detail'),
    url(r'^coursegroup/delete/(?P<pk>[0-9]+)$', views.CourseGroupDelete.as_view(),
        name='coursegroup_delete'),
    url(r'^coursegroup/edit/(?P<pk>[0-9]+)$', views.CourseGroupUpdate.as_view(),
        name='coursegroup_edit'),
    url(r'^coursegroup/create/$', views.CourseGroupCreate.as_view(),
        name='coursegroup_create'),
    url(r'^participants/$',
        views.ParticipantListView.as_view(), name='browse_participants'
        ),
    url(r'^participant/detail/(?P<pk>[0-9]+)$', views.ParticipantDetailView.as_view(),
        name='participant_detail'),
    url(r'^participant/delete/(?P<pk>[0-9]+)$', views.ParticipantDelete.as_view(),
        name='participant_delete'),
    url(r'^participant/edit/(?P<pk>[0-9]+)$', views.ParticipantUpdate.as_view(),
        name='participant_edit'),
    url(r'^participant/create/$', views.ParticipantCreate.as_view(),
        name='participant_create'),
]

delt/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from vocabs import api_views

if 'bib' in settings.INSTALLED_APPS:
    from bib.api_views import ZotItemViewSet

router = routers.DefaultRouter()
router.register(r'metadata', api_views.MetadataViewSet)
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skoscollections', api_views.SkosCollectionViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
if 'bib' in settings.INSTALLED_APPS:
    router.register(r'zotitems', ZotItemViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^assignments/', include('assignments.urls', namespace='assignments')),
    url(r'^admin/', admin.site.urls),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^shib/', include('shibboleth.urls', namespace='shibboleth')),
    url(r'^', include('webpage.urls', namespace='webpage')),
]

if 'bib' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^bib/', include('bib.urls', namespace='bib')),
    )

handler404 = 'webpage.views.handler404'

assignments/views.py
import datetime
import time
from io import BytesIO
from zipfile import ZipFile

from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponse


from django_tables2 import RequestConfig

from browsing.browsing_utils import GenericListView, BaseCreateView, BaseUpdateView
from webpage.utils import access_for_shib_and_loggedin

from . models import *
from . tables import *
from . filters import *
from . forms import *


class AssignmentListView(UserPassesTestMixin, GenericListView):
    model = Assignment
    table_class = AssignmentTable
    filter_class = AssignmentListFilter
    formhelper_class = AssignmentFilterFormHelper
    init_columns = [
        'id',
        'title',
    ]

    def test_func(self):
        access = access_for_shib_and_loggedin(self)
        print(access)
        return access

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(AssignmentListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by
        }).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class AssignmentDetailView(UserPassesTestMixin, DetailView):
    model = Assignment
    template_name = 'assignments/assignment_detail.html'

    def test_func(self):
        access = access_for_shib_and_loggedin(self)
        return access


class AssignmentCreate(BaseCreateView):

    model = Assignment
    form_class = AssignmentForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AssignmentCreate, self).dispatch(*args, **kwargs)


class AssignmentUpdate(BaseUpdateView):

    model = Assignment
    form_class = AssignmentForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AssignmentUpdate, self).dispatch(*args, **kwargs)


class AssignmentDelete(DeleteView):
    model = Assignment
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('assignments:browse_assignments')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AssignmentDelete, self).dispatch(*args, **kwargs)


class TextListView(UserPassesTestMixin, GenericListView):
    model = Text
    table_class = TextTable
    filter_class = TextListFilter
    formhelper_class = TextFilterFormHelper
    init_columns = [
        'legacy_id',
        'type',
    ]

    def test_func(self):
        access = access_for_shib_and_loggedin(self)
        return access

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(TextListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by
        }).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class TextDetailView(UserPassesTestMixin, DetailView):
    model = Text
    template_name = 'assignments/text_detail.html'

    def test_func(self):
        access = access_for_shib_and_loggedin(self)
        return access


class TextCreate(BaseCreateView):

    model = Text
    form_class = TextForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TextCreate, self).dispatch(*args, **kwargs)


class TextUpdate(BaseUpdateView):

    model = Text
    form_class = TextForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TextUpdate, self).dispatch(*args, **kwargs)


class TextDelete(DeleteView):
    model = Text
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('assignments:browse_texts')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TextDelete, self).dispatch(*args, **kwargs)


class TextVersionListView(UserPassesTestMixin, GenericListView):
    model = TextVersion
    table_class = TextVersionTable
    filter_class = TextVersionListFilter
    formhelper_class = TextVersionFilterFormHelper
    init_columns = [
        'legacy_id',
        'Plain_Text',
        'text_id__mode',
        'text_id__text_type',
    ]
    template_name = 'assignments/text_list.html'

    def test_func(self):
        access = access_for_shib_and_loggedin(self)
        return access

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(TextVersionListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [x for x in self.get_all_cols() if x not in self.init_columns]
        context['togglable_colums'] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by
        }).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table
    
    def render_to_response(self, context, **kwargs):
        download = self.request.GET.get('zip', None)
        download_plain = self.request.GET.get('zip_plain', None)
        if download:
            zipped_file = BytesIO()
            timestamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
            zip_name = f"export_{timestamp}.zip"
            texts = self.get_queryset()
            with ZipFile(zipped_file, 'w') as zipped:
                for x in texts:
                    file_name = f"text__{x.id}.txt"
                    zipped.writestr(file_name, f"{x.content}")
            zipped_file.seek(0)
            response = HttpResponse(zipped_file, content_type='application/octet-stream')
            response['Content-Disposition'] = f'attachment; filename={timestamp}.zip'
            return response
        elif download_plain:
            zipped_file = BytesIO()
            timestamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
            zip_name = f"export_{timestamp}.zip"
            texts = self.get_queryset()
            with ZipFile(zipped_file, 'w') as zipped:
                for x in texts:
                    file_name = f"text__{x.id}.txt"
                    zipped.writestr(file_name, f"{x.get_plain_text()}")
            zipped_file.seek(0)
            response = HttpResponse(zipped_file, content_type='application/octet-stream')
            response['Content-Disposition'] = f'attachment; filename={timestamp}.zip'
            return response
        else:
            response = super(GenericListView, self).render_to_response(context)
            return response  

class TextVersionDetailView(UserPassesTestMixin, DetailView):
    model = TextVersion
    template_name = 'assignments/textversion_detail.html'

    def test_func(self):
        access = access_for_shib_and_loggedin(self)
        return access


class TextVersionCreate(BaseCreateView):

    model = TextVersion
    form_class = TextVersionForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TextVersionCreate, self).dispatch(*args, **kwargs)


class TextVersionUpdate(BaseUpdateView):

    model = TextVersion
    form_class = TextVersionForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TextVersionUpdate, self).dispatch(*args, **kwargs)


class TextVersionDelete(DeleteView):
    model = TextVersion
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('assignments:browse_textversions')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TextVersionDelete, self).dispatch(*args, **kwargs)


class LearnerListView(UserPassesTestMixin, GenericListView):
    model = Learner
    table_class = LearnerTable
    filter_class = LearnerListFilter
    formhelper_class = LearnerFilterFormHelper
    init_columns = [
        'id',
        'title',
    ]

    def test_func(self):
        access = access_for_shib_and_loggedin(self)

assignments/templates/assignments/assignment_detail.html
{% extends "webpage/base.html" %}
{% load webpage_extras %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'assignments:assignment_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>Assignment:</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'assignments:assignment_edit' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'assignments:assignment_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'assignments:assignment_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
        <div class="card-body">
            <legend>
                Info
            </legend>
            <table class="table table-bordered table-hover">
                <tr>
                    <th>
                        {% get_verbose_name assignment "title" %}
                    </th>
                    <td>
                        {{ object.title }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name assignment "description" %}
                    </th>
                    <td>
                        {{ object.description }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name assignment "assignment_desc_link" %}
                    </th>
                    <td>
                        {{ object.assignment_desc_link }}
                    </td>
                </tr>
                <tr>
                    <th>
                        related texts
                    </th>
                    <td>
                        {% for x in object.has_text.all %}
                            <li>
                                <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                            </li>
                        {% endfor %}
                    </td>
                </tr>
            </table>
            {% if user.is_authenticated %}
                <legend>
                    internal info
                </legend>
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>
                            {% get_verbose_name assignment "legacy_id" %}
                        </th>
                        <td>
                            {{ object.legacy_id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {% get_verbose_name assignment "entered_by" %}
                        </th>
                        <td>
                            {{ object.entered_by }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {% get_verbose_name assignment "entered_date" %}
                        </th>
                        <td>
                            {{ object.entered_date }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {% get_verbose_name assignment "last_changed" %}
                        </th>
                        <td>
                            {{ object.last_changed }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {% get_verbose_name assignment "notes" %}
                        </th>
                        <td>
                            {{ object.notes }}
                        </td>
                    </tr>
                </table>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

assignments/templates/assignments/text_detail.html
{% extends "webpage/base.html" %}
{% load webpage_extras %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'assignments:text_detail' pk=object.get_prev %}">
                                <i class="fas fa-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>Text:</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'assignments:text_edit' pk=object.id %}">
                                    <i class="far fa-edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'assignments:text_delete' pk=object.id %}">
                                    <i class="far fa-trash-alt" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'assignments:text_detail' pk=object.get_next %}" style="float:right">
                        <i class="fas fa-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
        <div class="card-body">
            <legend>
                Info
            </legend>
            <table class="table table-bordered table-hover">
                <tr>
                    <th>
                        {% get_verbose_name text "participant_id" %}
                    </th>
                    <td>
                        {{ object.participant_id }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "text_type" %}
                    </th>
                    <td>
                        {{ object.text_type }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "assignment_id" %}
                    </th>
                    <td>
                        <a href="{{ object.assignment_id.get_absolute_url }}">
                            {{ object.assignment_id }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "availability" %}
                    </th>
                    <td>
                        {{ object.availability }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "year" %}
                    </th>
                    <td>
                        {{ object.year }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "semester" %}
                    </th>
                    <td>
                        {{ object.semester }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "lang" %}
                    </th>
                    <td>
                        {{ object.lang }} - MISTAKE IN IMPORT SCRIPT
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "medium" %}
                    </th>
                    <td>
                        {{ object.medium }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "data_type" %}
                    </th>
                    <td>
                        {{ object.data_type }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "recording" %}
                    </th>
                    <td>
                        {{ object.recording }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "recoding_method" %}
                    </th>
                    <td>
                        {{ object.recoding_method }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "mode" %}
                    </th>
                    <td>
                        {{ object.mode }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "clil_text" %}
                    </th>
                    <td>
                        {{ object.clil_text }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "clil_subject" %}
                    </th>
                    <td>
                        {{ object.clil_subject }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "timed" %}
                    </th>
                    <td>
                        {{ object.timed }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "exam" %}
                    </th>
                    <td>
                        {{ object.exam }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "planning_time" %}
                    </th>
                    <td>
                        {{ object.planning_time }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "tool" %}
                    </th>
                    <td>
                        {{ object.tool }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "grade" %}
                    </th>
                    <td>
                        {{ object.grade }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "title" %}
                    </th>
                    <td>
                        {{ object.title }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "source" %}
                    </th>
                    <td>
                        {{ object.source }}
                    </td>
                </tr>
                {% if object.transcriber %}
                    <tr>
                        <th>
                            {% get_verbose_name text "transcriber" %}
                        </th>
                        <td>
                            <a href="{{ object.transcriber.get_absolute_url }}">
                                {{ object.transcriber }}
                            </a>
                        </td>
                    </tr>
                {% endif %}
                {% if object.has_text_version.all %}
                    <tr>
                        <th>
                            related text versions
                        </th>
                        <td>
                            {% for x in object.has_text_version.all %}
                                <li>
                                    <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                                </li>
                            {% endfor %}
                        </td>
                    </tr>
                {% endif %}
            </table>









            <legend>
                internal info
            </legend>
            <table class="table table-bordered table-hover">
                <tr>
                    <th>
                        {% get_verbose_name text "legacy_id" %}
                    </th>
                    <td>
                        {{ object.legacy_id }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "entered_by" %}
                    </th>
                    <td>
                        {{ object.entered_by }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "entered_date" %}
                    </th>
                    <td>
                        {{ object.entered_date }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "last_changed" %}
                    </th>
                    <td>
                        {{ object.last_changed }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name text "notes" %}
                    </th>
                    <td>
                        {{ object.notes }}
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}