assignments/urls.py
from django.conf.urls import url
from . import views

app_name = 'assignments'

urlpatterns = [
    url(r'^assignments/$', views.AssignmentListView.as_view(), name='browse_assignments'),
    url(r'^assignment/detail/(?P<pk>[0-9]+)$', views.AssignmentDetailView.as_view(),
        name='assignment_detail'),
    url(r'^assignment/delete/(?P<pk>[0-9]+)$', views.AssignmentDelete.as_view(),
        name='assignment_delete'),
    url(r'^assignment/edit/(?P<pk>[0-9]+)$', views.AssignmentUpdate.as_view(),
        name='assignment_edit'),
    url(r'^assignment/create/$', views.AssignmentCreate.as_view(),
        name='assignment_create'),
    url(r'^texts/$', views.TextListView.as_view(), name='browse_texts'),
    url(r'^text/detail/(?P<pk>[0-9]+)$', views.TextDetailView.as_view(),
        name='text_detail'),
    url(r'^text/delete/(?P<pk>[0-9]+)$', views.TextDelete.as_view(),
        name='text_delete'),
    url(r'^text/edit/(?P<pk>[0-9]+)$', views.TextUpdate.as_view(),
        name='text_edit'),
    url(r'^text/create/$', views.TextCreate.as_view(),
        name='text_create'),
    url(r'^textversions/$', views.TextVersionListView.as_view(), name='browse_textversions'),
    url(r'^textversion/detail/(?P<pk>[0-9]+)$', views.TextVersionDetailView.as_view(),
        name='textversion_detail'),
    url(r'^textversion/delete/(?P<pk>[0-9]+)$', views.TextVersionDelete.as_view(),
        name='textversion_delete'),
    url(r'^textversion/edit/(?P<pk>[0-9]+)$', views.TextVersionUpdate.as_view(),
        name='textversion_edit'),
    url(r'^textversion/create/$', views.TextVersionCreate.as_view(),
        name='textversion_create'),
    url(r'^learners/$', views.LearnerListView.as_view(), name='browse_learners'),
    url(r'^learner/detail/(?P<pk>[0-9]+)$', views.LearnerDetailView.as_view(),
        name='learner_detail'),
    url(r'^learner/delete/(?P<pk>[0-9]+)$', views.LearnerDelete.as_view(),
        name='learner_delete'),
    url(r'^learner/edit/(?P<pk>[0-9]+)$', views.LearnerUpdate.as_view(),
        name='learner_edit'),
    url(r'^learner/create/$', views.LearnerCreate.as_view(),
        name='learner_create'),
    url(r'^learnerprofiles/$',
        views.LearnerProfileListView.as_view(), name='browse_learnerprofiles'
        ),
    url(r'^learnerprofile/detail/(?P<pk>[0-9]+)$', views.LearnerProfileDetailView.as_view(),
        name='learnerprofile_detail'),
    url(r'^learnerprofile/delete/(?P<pk>[0-9]+)$', views.LearnerProfileDelete.as_view(),
        name='learnerprofile_delete'),
    url(r'^learnerprofile/edit/(?P<pk>[0-9]+)$', views.LearnerProfileUpdate.as_view(),
        name='learnerprofile_edit'),
    url(r'^learnerprofile/create/$', views.LearnerProfileCreate.as_view(),
        name='learnerprofile_create'),
    url(r'^coursegroups/$',
        views.CourseGroupListView.as_view(), name='browse_coursegroups'
        ),
    url(r'^coursegroup/detail/(?P<pk>[0-9]+)$', views.CourseGroupDetailView.as_view(),
        name='coursegroup_detail'),
    url(r'^coursegroup/delete/(?P<pk>[0-9]+)$', views.CourseGroupDelete.as_view(),
        name='coursegroup_delete'),
    url(r'^coursegroup/edit/(?P<pk>[0-9]+)$', views.CourseGroupUpdate.as_view(),
        name='coursegroup_edit'),
    url(r'^coursegroup/create/$', views.CourseGroupCreate.as_view(),
        name='coursegroup_create'),
    url(r'^participants/$',
        views.ParticipantListView.as_view(), name='browse_participants'
        ),
    url(r'^participant/detail/(?P<pk>[0-9]+)$', views.ParticipantDetailView.as_view(),
        name='participant_detail'),
    url(r'^participant/delete/(?P<pk>[0-9]+)$', views.ParticipantDelete.as_view(),
        name='participant_delete'),
    url(r'^participant/edit/(?P<pk>[0-9]+)$', views.ParticipantUpdate.as_view(),
        name='participant_edit'),
    url(r'^participant/create/$', views.ParticipantCreate.as_view(),
        name='participant_create'),
]

delt/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from vocabs import api_views

if 'bib' in settings.INSTALLED_APPS:
    from bib.api_views import ZotItemViewSet

router = routers.DefaultRouter()
router.register(r'metadata', api_views.MetadataViewSet)
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skoscollections', api_views.SkosCollectionViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
if 'bib' in settings.INSTALLED_APPS:
    router.register(r'zotitems', ZotItemViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^assignments/', include('assignments.urls', namespace='assignments')),
    url(r'^admin/', admin.site.urls),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^shib/', include('shibboleth.urls', namespace='shibboleth')),
    url(r'^', include('webpage.urls', namespace='webpage')),
]

if 'bib' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^bib/', include('bib.urls', namespace='bib')),
    )

handler404 = 'webpage.views.handler404'

webpage/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

app_name = 'webpage'

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    url(r'^favicon\.ico$', favicon_view),
    url(r'^$', views.GenericWebpageView.as_view(), name="start"),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^project-info/$', views.project_info, name='project_info'),
    url(r'^(?P<template>[\w-]+)/$', views.GenericWebpageView.as_view(), name='staticpage'),
]

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class form_user_login(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(form_user_login, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'login'))

webpage/views.py
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout
from .forms import form_user_login


class GenericWebpageView(TemplateView):
    template_name = 'webpage/index.html'

    def get_context_data(self, **kwargs):
        context = super(GenericWebpageView, self).get_context_data(**kwargs)
        context['apps'] = settings.INSTALLED_APPS
        context['meta'] = self.request.META
        return context

    def get_template_names(self):
        template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        try:
            loader.select_template([template_name])
            template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        except:
            template_name = "webpage/index.html"
        return [template_name]


#################################################################
#               views for login/logout                          #
#################################################################

def user_login(request):
    if request.method == 'POST':
        form = form_user_login(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.GET.get('next', '/'))
            return HttpResponse('user does not exist')
    else:
        form = form_user_login()
        return render(request, 'webpage/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return render(request, 'webpage/user_logout.html')


def handler404(request, exception):
    return render(request, 'webpage/404-error.html', locals())

webpage/templates/webpage/404-error.html
{% extends "webpage/base.html" %}
{% load static %}

{% block content %}
<div class="container">
<div style="text-align: center;">
    
    <h2>We're sorry, the page you requested cannot be found.</h2>
    <p style="text-align: center">The page you're trying to access may not exist anymore or may have been moved. Try accessing it again from our site's homepage. Please also make sure that your spelling is correct.</p>
    <p style="text-align: center">If the problem persists, please report it as an issue <a href="https://github.com/acdh-oeaw/delt/issues">here</a>. Thank you!</p>

</div>
</div>
{% endblock %}

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} About {% endblock %}
{% block content %}
<div class="container">
    <div class="card">

        <div class="card-body">
            <div>
                <h3>About</h3>
                <p>
                    The Database of English Learner Texts (DELT) aims to promote research on the learning and use of English. The database is freely available to all members of the research community, provided they adhere to the <a href="/terms-of-use"><strong>conditions of use</strong></a> (see below). The database consists of a collection of texts (both written and oral) produced by learners of English. Background information on the texts and authors allows users of DELT to find texts that share certain characteristics, such as language proficiency level, text type/genre, modality etc. The resulting text corpora can then be analysed with tools such as <a href="http://www.laurenceanthony.net/software/antwordprofiler/"><strong>AntWord®</strong></a>, <a href="https://www.lexically.net/wordsmith/"><strong>WordSmith®</strong></a>or others.
                <p>
                    The majority of participants have German as their dominant language and produced these texts in school or university settings. More detailed information on the texts and participants is provided in each text header.
                </p>
                </p>
                <h3>Acknowledgements</h3>
                DELT is a project of the <a href="https://celt.univie.ac.at/"><strong>Centre for English Language Teaching (CELT)</strong></a>. It has received internal funding from the <a href="https://www.univie.ac.at/"><strong>University of Vienna</strong></a>.
                <div class="row justify-content-center" style="padding:10px;">
                    <div class="col-4" style="padding:10px;">
                        <img src="{% static 'webpage/img/celt-logo.png' %}" alt="CELT" title="CENTRE FOR ENGLISH LANGUAGE TEACHING"/>
                    </div>
                    <div class="col-4" style="padding:10px;">
                        <img src="{% static 'webpage/img/partner_logo.png' %}" alt="Partner Logo" title="Partner Logo" width="70%"/>
                    </div>
                </div>
                <h3>Team</h3>
                <p>
                    <ul>
                        <li>
                            <a href="https://anglistik.univie.ac.at/staff/staff/detail-seite/user/boniecm2/inum/1063/backpid/30750">Mmag. Monika Boniecki</a>
                        </li>
                        <li>
                            <a href="https://anglistik.univie.ac.at/staff/staff/detail-seite/user/daltonc8/inum/1063/backpid/30750">Prof. Christiane Dalton-Puffer</a>
                        </li>
                        <li>
                            <a href="https://anglistik.univie.ac.at/staff/staff/detail-seite/user/huettnj8/inum/1063/backpid/30750">Prof. Julia Hüttner</a>
                        </li>
                        <li>
                            <a href="https://anglistik.univie.ac.at/staff/staff/detail-seite/user/mehlmab8/inum/1063/backpid/30750">Dr. Barbara Mehlmauer-Larcher </a>
                        </li>
                        <li>
                            <a href="https://www.bg-porcia.at/kollegium/schiftner-barbara/">Dr. Barbara Schiftner </a>
                        </li>
                    </ul>
                    <small>All can be contacted at <a href="mailto:celt@univie.ac.at"><strong>celt@univie.ac.at</strong></a></small>
                </p>
                <h3>PUBLICATIONS</h3>
                <p>
                    <ul>
                        <li>
                            Schiftner, Barbara M. 2017. “An integrative approach to discourse coherence: rhetorical structure and cohesion in university students' English L2 writing”. PhD thesis, Department of English and American Studies, University of Vienna.
                        </li>
                    </ul>
                </p>
                <h3>PARTICIPATION</h3>
                <p>
                    DELT is intended as a growing repository of learner texts. If you wish to take part by contributing texts, please get in touch with us at <a href="mailto:celt@univie.ac.at"><strong>celt@univie.ac.at</strong></a>
                </p>
                <h3>FEEDBACK</h3>
                <p>
                    We’re interested to know how you are getting on with using DELT and if you have any feedback for us. If so, please contact us at <a href="mailto:celt@univie.ac.at"><strong>celt@univie.ac.at</strong></a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

webpage/templates/webpage/base.html
<!DOCTYPE html>
{% load static %}
{% load webpage_extras %}
{% load browsing_extras %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% projects_metadata 'title' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block metaDescription %}
        <meta name="description" content="{{ metadata.description }}">
        <meta name="author" content="{{ metadata.author }}">
    {% endblock %}
    <!-- favicons -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'webpage/img/favicon/apple-touch-icon.png' %}"/>
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'webpage/img/favicon/favicon-32x32.png' %}"/>
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'webpage/img/favicon/favicon-16x16.png' %}"/>
        <link rel="manifest" href="{% static 'webpage/img/favicon/manifest.json' %}"/>
        <link rel="mask-icon" href="{% static 'webpage/img/favicon/safari-pinned-tab.svg' %}" color="#00aba9"/>
        <meta name="theme-color" content="#ffffff"/>
    <!--favicons end -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin:400,500" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'webpage/css/fundament.css' %}" rel="stylesheet"/>
    <!-- <link rel="stylesheet" href="{% static 'webpage/css/fundament_new.css' %}" rel="stylesheet"/> -->
    <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}" />
    <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
    <script type="text/javascript">
        window.cookieconsent_options = {
            "message":"This website uses cookies to ensure you get the best experience on our website",
            "dismiss":"Got it!",
            "learnMore":"More info",
            "link":"{% projects_metadata 'imprint' %}",
            "theme":"dark-bottom"};
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
    <!-- End Cookie Consent plugin -->
    <!-- Matomo -->
      <script type="text/javascript">
        var _paq = _paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
          var u="{% projects_metadata 'matomo_url' %}";
          _paq.push(['setTrackerUrl', u+'piwik.php']);
          _paq.push(['setSiteId', '{% projects_metadata "matomo_id" %}']);
          var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
          g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
        })();
      </script>
    <!-- End Matomo Code -->
    {% block scriptHeader %}
    {% endblock %}
</head>
<body role="document" class="contained fixed-nav">
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top bg-white box-shadow">
            <a class="navbar-brand" href="/">
                <img src="{% static 'webpage/img/celt-logo.png' %}" alt="CELT" title="CENTRE FOR ENGLISH LANGUAGE TEACHING"/>
            </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About
                                <span class="caret"/>
                            </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'webpage:staticpage' template='about' %}">About</a>
                                    <a class="dropdown-item" href="{% url 'webpage:staticpage' template='terms-of-use' %}">Terms of Use</a>
                                    <a class="dropdown-item" href="{% url 'webpage:staticpage' template='imprint' %}">Imprint | Impressum</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                {% if SHIB or user.is_authenticated %}
                                <a href="{% url 'assignments:browse_textversions' %}" class="nav-link" role="button" aria-haspopup="true" aria-expanded="false">Browse Texts
                                {% else %}
                                {% endif %}
                            </li>
                    {% if SHIB or user.is_authenticated %}
                    <li class="nav-item dropdown ml-auto">
                        <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ user.get_username }} {{ SHIB }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="nav-link" href="{% url 'webpage:user_logout' %}">Log-Out</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item dropdown ml-auto">
                        <a class="nav-link" href="{% url 'webpage:user_login' %}">
                        <i class="fas fa-sign-in-alt"></i>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <div class="navbar-icons">
                    <a href="{% projects_metadata 'github' %}" target="_blank" rel="noopener">
                        <i class="fab fa-github"></i>
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <section class="main-content">
        {% if DEV_VERSION %}
        <div class="alert alert-danger" role="alert">
            This is a the DEVELOPMENT instance. Click <a href="https://delt.acdh.oeaw.ac.at">here</a> for the Production version
        </div>
        {% endif %}
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </section>
    <footer class="main-footer">
        <div class="container">
            <div class="footer-wrapper">
                <div class="footer-sep">
                    <i class="far fa-comment"></i> CONTACT
                </div>
            <div class="row">
                <div class="col-md-2 pl-0">
                    <a href="https://www.oeaw.ac.at/acdh/acdh-home/" target="_blank" rel="noopener" aria-label="ACDH">
                        <img src="{% static 'webpage/img/acdh_logo.png' %}" alt="ACDH" title="Austrian Centre for Digital Humanities"/>
                    </a>
                </div>
                <div class="col-md-2 ml-auto">
                    <img src="{% static 'webpage/img/partner_logo.png' %}" alt="Partner Logo" title="Partner Logo"/>
                </div>
            </div>

            </div>
        </div>
            </div>
            <div class="footer-imprint-bar">
                <a href="{% projects_metadata 'imprint' %}">Impressum/Imprint</a> | <a href="/terms-of-use">Terms of Use</a>
                {% if SHIB or user.is_authenticated %}
                    {% if DB_NAME %}
                        <div class="footer-imprint-bar">
                            <small>{{ DB_NAME }}</small>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </footer>
        {% block scripts %}
        <script src="https://fundament.acdh.oeaw.ac.at/dist/fundament/vendor/js/fontawesome-all.min.js"></script>
        <script src="https://fundament.acdh.oeaw.ac.at/dist/fundament/js/fundament.min.js"></script>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css" />
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
        <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $.apScrollTop({'onInit': function(evt) {console.log('apScrollTop: init');}});
            });
        </script>
        {% endblock %}
        {% block scripts2 %}
        {% endblock scripts2 %}
        <noscript>
            <img src="//piwik.apollo.arz.oeaw.ac.at/piwik.php?idsite=48" style="border:0;" alt=""/>
        </noscript>
        </body>
        </html>

webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong>{{ object }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn" type="submit" value="No, bring me back" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

webpage/templates/webpage/index.html
{% extends "webpage/base.html" %}
{% load static %}
{% load stats_extras %}
{% load webpage_extras %}
{% block content %}

        <div class="jumbotron" style="background-image: url({% static 'webpage/img/project_background.jpg' %}) ">
            <div class="container">
                <h1 style="text-align:center; color: #111;">{% projects_metadata 'title' %}</h1>
                <h3 style="text-align:center; color: #111;">{% projects_metadata 'subtitle' %}</h3>
                <p style="color: #111;">
                    The Database of English Learner Texts (DELT) aims to promote research on the learning and use of English. The database is freely available to all members of the research community, provided they adhere to the <a href="/terms-of-use"><strong>conditions of use</strong></a> (see below). The database consists of a collection of texts (both written and oral) produced by learners of English. Background information on the texts and authors allows users of DELT to find texts that share certain characteristics, such as language proficiency level, text type/genre, modality etc. The resulting text corpora can then be analysed with tools such as <a href="http://www.laurenceanthony.net/software/antwordprofiler/"><strong>AntWord®</strong></a>, <a href="https://www.lexically.net/wordsmith/"><strong>WordSmith®</strong></a>or others. The majority of participants have German as their dominant language and produced these texts in school or university settings. More detailed information on the texts and participants is provided in each text header.
                </p>
                <a href="/about" type="button" class="btn btn-secondary btn btn-lg explore">About the Project</a>
                {% if SHIB or user.is_authenticated %}
                    <a href="/assignments/textversions/" type="button" class="btn btn-secondary btn-lg explore">Explore the Data</a>
                {% else %}
                    <a href="/Shibboleth.sso/Login" type="button" class="btn btn-secondary btn-lg explore">log in with shib</a>
                {% endif %}
            </div>
        </div>



{% endblock %}

webpage/templates/webpage/user_login.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <br />
    {% if form.errors %}
        <p style="color:red;">Please correct the error{{ form.errors|pluralize }} below.</p>
    {% endif %}
    {% load crispy_forms_tags %}
    {% crispy form form.helper %}

    {% if 'shibboleth' in APPS %}
        <a href="/Shibboleth.sso/Login" type="button" class="btn btn-secondary">log in with shib</a>
    {% endif %}
</div>
{% endblock %}

webpage/templates/webpage/user_logout.html
{% extends "webpage/base.html" %}
{% block title %}logout{% endblock %}
{% block content %}
<div class="jumbotron container" style="color:black;">
    <h1>Sayōnara!</h1>
    <p>You've signed out</p>
</div>
{% endblock content %}